[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dataset",
    "lightning>=2.6.1",
    "matplotlib>=3.10.8",
    "mlflow==3.12.0",
    "optuna>=4.8.0",
    "pandas>=2.3.3",
    "pip>=26.0.1",
    "psycopg2-binary>=2.9.11",
    "seaborn>=0.13.2",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]

[tool.basedpyright]
typeCheckingMode = "basic"
reportPrivateImportUsage = false

[tool.uv.sources]
dataset = { path = "packages/dataset", editable = true }
